services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: dbt_user
      POSTGRES_PASSWORD: dbt_pass
      POSTGRES_DB: dbt_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:latest
    container_name: dbt
    depends_on:
      - postgres
    volumes:
      - ./dbt_project:/usr/app
      - ./profiles:/root/.dbt
    working_dir: /usr/app
    entrypoint: ["sleep", "infinity"]


volumes:
  postgres_data: